### PR TITLE
Fix CreateRepository for GitLab provider

### LINKED ISSUE #22: Adding Deploy Key for GitLab tries to use the wrong project
The list projects method actually does a search and naïvely grabs the first one it finds. e.g. if you have a repo called manifests it will execute a search like this https://gitlab.com/search?search=manifests and grab https://gitlab.com/evolution-x-sakura/local_manifests_sakura as the project to add the key to. This will fail for obvious reasons.

### PR DESCRIPTION
**Pull request by relu**
Ensure projects are discovered using the correct method in the case of group owned projects (ListGroupProjects) vs personal owned projects (ListProjects).

The issue can be reproduced when bootstrapping on GitLab with a personal account and using a repository name that could already belong to another user.

This is from a user report in [slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1607540221358200).

Fixes #22.

### CODE REVIEW

**Comment by relu** [comment]
I've tested this locally with `flux2` with the following use cases:

1. Is able to create personal repo: `flux bootstrap gitlab --owner=personalacc --repository=flux --personal --token-auth --branch=master`
2. Is able to discover the previously created repo (command re-execution).
3. Is able to create group owned repo: `flux bootstrap gitlab --owner=groupacc --repository=flux --token-auth --branch=master`
4. Is able to discover the previously created repo (command re-execution).

File: git/provider_gitlab.go [hunk 1]
```diff
@@ -56,15 +56,37 @@ func (p *GitLabProvider) CreateRepository(ctx context.Context, r *Repository) (b
...
 
 		if len(groups) > 0 {
-			id = &groups[0].ID
+			gid = &groups[0].ID
+		}
+
+		lpo := &gitlab.ListGroupProjectsOptions{
+			Search: gitlab.String(r.Name),
+		}
+		projects, _, err = gl.Groups.ListGroupProjects(*gid, lpo, gitlab.WithContext(ctx))
```
Comment (relu) [inline git/provider_gitlab.go:78]: Note: This method will retrieve only repos in the context of `gid`.

File: git/provider_gitlab.go [hunk 2]
```diff
@@ -56,15 +56,37 @@ func (p *GitLabProvider) CreateRepository(ctx context.Context, r *Repository) (b
...
+		if err != nil {
+			return false, fmt.Errorf("failed to list projects, error: %w", err)
+		}
+	} else {
+		lpo := &gitlab.ListProjectsOptions{
+			Search: gitlab.String(r.Name),
+			Owned:  gitlab.Bool(true),
```
Comment (relu) [inline git/provider_gitlab.go:85]: Note: This ensures the listing includes only repositories owned by the current user. Lacking this was the cause of the original user-reported issue.

**Comment by stefanprodan** [comment]
This fixes #22?

**Comment by relu** [comment]
No, but I can probably fix that in the scope of this PR as well. Wasn't aware of the issue, it's definitely similar in nature.

**Comment by relu** [comment]
I've tested deploy key creation in the scenarios previously mentioned and I can confirm it works with these changes now.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @relu 🥇
